constraint_value(
    name = "armv6-m",
    constraint_setting = "@platforms//cpu:cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "armv7-m",
    constraint_setting = "@platforms//cpu:cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "armv7e-m",
    constraint_setting = "@platforms//cpu:cpu",
    visibility = ["//visibility:public"],
)

# TODO(cfrantz): Upstream to https://github.com/bazelbuild/platforms
constraint_value(
    # Based on the current riscv64 consrtaint in platforms, I wonder
    # if this should be `riscv32` or `rv32imc`.
    name = "rv32imc",
    constraint_setting = "@platforms//cpu:cpu",
    visibility = ["//visibility:public"],
)
